# serverless.yml

service: threebox-graphql
provider:
  name: aws
  runtime: nodejs8.10
  stage: develop
  region: us-west-2
plugins:
  - serverless-offline
functions:
  graphql:
    handler: src/index.graphqlHandler
    events:
    - http:
        path: graphql
        method: post
        cors: true
