# serverless.yml

service: threebox-graphql
provider:
  name: aws
  runtime: nodejs8.10
  stage: develop
  region: us-west-2
  environment:
    PROFILE_SERVER_URL: https://ipfs.3box.io

plugins:
  - serverless-offline

custom:
  serverless-offline:
    host: 0.0.0.0

functions:
  graphql:
    handler: src/index.graphqlHandler
    events:
    - http:
        path: /
        method: post
        cors: true
    - http:
        path: graphql
        method: post
        cors: true
